#ifndef DAIVIK_KERNEL_DESCRIPTORS_INTERRUPT_DESCRIPTOR_TABLE_HXX
#define DAIVIK_KERNEL_DESCRIPTORS_INTERRUPT_DESCRIPTOR_TABLE_HXX 1

/// kernel namespace
namespace kernel{



} // kernel namespace

#endif//DAIVIK_KERNEL_DESCRIPTORS_INTERRUPT_DESCRIPTOR_TABLE_HXX